export const ticketList = [
    {
        idIngresso: 1,
        idOrganizador: 23,
        nome: 'Show do BTS',
        data: '19/12/2021',
        horario: '15:00',
        endereco: 'Rua sei la mano',
        preco: 300,
        descricao: 'KKKK show dos coreano que dança kkkkkkkk',
        qtdIngressos: 1200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://i.ytimg.com/vi/LHpyn6DnMVI/maxresdefault.jpg',
        categoria: 'Musica',
    },
    {
        idIngresso: 2,
        idOrganizador: 12,
        nome: 'Palmeiras X Flamengo',
        data: '27/11/2021',
        horario: '17:00',
        endereco: 'Rua sei la mano',
        preco: 980,
        descricao: 'Jogo da final da libertadores',
        qtdIngressos: 1200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://www.gazetaesportiva.com/wp-content/uploads/imagem/2020/12/08/flamengo-palmeiras-brasileiro.jpg',
        categoria: 'Esporte',
    },
    {
        idIngresso: 3,
        idOrganizador: 14,
        nome: 'Luccas Neto Cover',
        data: '17/12/2021',
        horario: '10:00',
        endereco: 'Rua sei la mano',
        preco: 15,
        descricao: 'Show do Luccas Neto Cover',
        qtdIngressos: 150,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://avaazdo.s3.amazonaws.com/a88f1659bc1f0fc1bd3b253024c67daf.jpg',
        categoria: 'Teatro',
    },
    {
        idIngresso: 4,
        idOrganizador: 77,
        nome: 'Homem-Aranha 3',
        data: '17/12/2021',
        horario: '00:00',
        endereco: 'Rua sei la mano',
        preco: 50,
        descricao: 'KKKK show dos coreano que dança kkkkkkkk',
        qtdIngressos: 11200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://legadodamarvel.com.br/wp-content/uploads/2021/10/descricao-trailer-homem-aranha-3-legadodamarvel.jpg',
        categoria: 'Cinema',
    },
    {
        idIngresso: 5,
        idOrganizador: 14,
        nome: 'Show do Péricles',
        data: '11/12/2021',
        horario: '20:00',
        endereco: 'Rua sei la mano',
        preco: 90,
        descricao: 'Grande périclão',
        qtdIngressos: 300,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdx3E7ylgUYGVg7KoT5VySy1Kri7Qr7AI54Q&usqp=CAU',
        categoria: 'Musica',
    },
    {
        idIngresso: 6,
        idOrganizador: 78,
        nome: 'City X Psg',
        data: '24/11/2021',
        horario: '17:00',
        endereco: 'Algum lugar na ingleterra',
        preco: 1300,
        descricao: 'Fase de grupos da champions',
        qtdIngressos: 78000,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://androoapp.com/wp-content/uploads/2021/05/image.png',
        categoria: 'Esporte',
    },
]