export const ticketList = [
    {
        idIngresso: 1,
        organizer: {
            id: 4,
            nome: 'leoncião da massa'
        },
        nome: 'Show do BTS',
        data: '19/12/2021',
        horario: '15:00',
        endereco: 'Rua sei la mano',
        preco: 300,
        descricao: 'KKKK show dos coreano que dança kkkkkkkk',
        qtdIngressos: 1200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://i.ytimg.com/vi/LHpyn6DnMVI/maxresdefault.jpg',
        categoria: 'Musica',
    },
    {
        idIngresso: 2,
        organizer: {
            id: 6,
            nome: 'Conmebol Libertadores'
        },
        nome: 'Palmeiras X Flamengo',
        data: '27/11/2021',
        horario: '17:00',
        endereco: 'Rua sei la mano',
        preco: 980,
        descricao: 'Jogo da final da libertadores',
        qtdIngressos: 1200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://www.gazetaesportiva.com/wp-content/uploads/imagem/2020/12/08/flamengo-palmeiras-brasileiro.jpg',
        categoria: 'Esporte',
    },
    {
        idIngresso: 3,
        idOrganizador: 14,
        nome: 'Luccas Neto Cover',
        data: '17/12/2021',
        horario: '10:00',
        endereco: 'Rua sei la mano',
        preco: 15,
        descricao: 'Show do Luccas Neto Cover',
        qtdIngressos: 150,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://avaazdo.s3.amazonaws.com/a88f1659bc1f0fc1bd3b253024c67daf.jpg',
        categoria: 'Teatro',
    },
    {
        idIngresso: 4,
        idOrganizador: 77,
        nome: 'Homem-Aranha 3',
        data: '17/12/2021',
        horario: '00:00',
        endereco: 'Rua sei la mano',
        preco: 50,
        descricao: 'KKKK show dos coreano que dança kkkkkkkk',
        qtdIngressos: 11200,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://legadodamarvel.com.br/wp-content/uploads/2021/10/descricao-trailer-homem-aranha-3-legadodamarvel.jpg',
        categoria: 'Cinema',
    },
    {
        idIngresso: 5,
        idOrganizador: 14,
        nome: 'Show do Péricles',
        data: '11/12/2021',
        horario: '20:00',
        endereco: 'Rua sei la mano',
        preco: 90,
        descricao: 'Grande périclão',
        qtdIngressos: 300,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdx3E7ylgUYGVg7KoT5VySy1Kri7Qr7AI54Q&usqp=CAU',
        categoria: 'Musica',
    },
    {
        idIngresso: 6,
        idOrganizador: 78,
        nome: 'City X Psg',
        data: '24/11/2021',
        horario: '17:00',
        endereco: 'Algum lugar na ingleterra',
        preco: 1300,
        descricao: 'Fase de grupos da champions',
        qtdIngressos: 78000,
        status: 'VENDA',
        porcentagemDesconto: 0,
        fotoEvento: 'https://androoapp.com/wp-content/uploads/2021/05/image.png',
        categoria: 'Esporte',
    },
    {
        "id": 6,
        "organizer": {
            "id": 3,
            "role": {
                "id": 1,
                "role": "Vendedor"
            },
            "nome": "Leoncião da massa",
            "cpfCnpj": "12345678921",
            "telefoneContato": "11987875476",
            "fotoPerfil": "http://pm1.narvii.com/6543/7ef43f546272d309c4f9ff22a6e673a56d81d132_00.jpg",
            "dataNascimento": "1946-07-12T00:00:00.000+00:00",
            "email": "leoncio@gmail.com",
            "senha": "603494fec14a5c03726e02928d9dc2e0"
        },
        "nome": "Leoncião da massa",
        "data": "2022-03-11T02:30:00.000+00:00",
        "horario": "23:30:00",
        "endereco": "Praça das bandeiras",
        "preco": 12.5,
        "descricao": "Bailão rave funk do leoncio",
        "qtdIngressos": 150,
        "status": "DISPONÍVEL",
        "porcentagemDesconto": 10,
        "fotoEvento": "https://django-metabuscador.s3.amazonaws.com/static/home/images/no-photo.png",
        "categoria": "Musica"
    }
]